[package]
name = "optionable_codegen_cli"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
description = "Implementation of the codegen cli"
repository = "https://github.com/ngergs/optionable"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

[features]
default = []
k8s_openapi = ["optionable_codegen/k8s_openapi"]
kube = ["optionable_codegen/kube"]

[lints.clippy]
pedantic = "warn"

[dependencies]
optionable_codegen = "0.12.1"
quote = "1.0.43"
syn = { version = "2.0.114", default-features = false, features = ["proc-macro", "derive", "visit"] }
proc-macro2 = "1.0.105"
darling = { version = "0.23.0", default-features = false }
clap = { version = "4.5.54", features = ["derive"] }
prettyplease = "0.2.37"

[dev-dependencies]
assert_cmd = "2.1.2"
tempfile = "3.24.0"
