name: Release-plz

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release:
        description: Whether to actually run release-plz
        type: boolean
        required: true

jobs:
  k8s-openapi-roundtrip:
    name: k8s-openapi roundtrip test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: k8s-openapi roundtrip test
        run: |-
          echo 'k8s-openapi = { git = "https://github.com/ngergs/k8s-openapi" }' >> Cargo.toml
          cargo +nightly test --manifest-path=optionable/Cargo.toml --features k8s-openapi/std,k8s_openapi_convert,k8s_openapi_v1_30
          cargo +nightly test --manifest-path=optionable/Cargo.toml --features k8s-openapi/std,k8s_openapi_convert,k8s_openapi_v1_31
          cargo +nightly test --manifest-path=optionable/Cargo.toml --features k8s-openapi/std,k8s_openapi_convert,k8s_openapi_v1_32
          cargo +nightly test --manifest-path=optionable/Cargo.toml --features k8s-openapi/std,k8s_openapi_convert,k8s_openapi_v1_33
          cargo +nightly test --manifest-path=optionable/Cargo.toml --features k8s-openapi/std,k8s_openapi_convert,k8s_openapi_v1_34
        env:
          RUSTFLAGS: "--cfg test_k8s_openapi_roundtrip"
  # Release unpublished packages.
  release-plz-release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged }}
    needs: k8s-openapi-roundtrip
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Pre-release tests
        run: |-
          cargo +nightly docs-rs -p optionable
          cargo +nightly test --manifest-path=optionable/Cargo.toml --features derive,kube,k8s-openapi/v1_34
          cargo +nightly test --manifest-path=optionable/Cargo.toml --no-default-features --features derive,chrono,serde_json
          cargo +nightly test --manifest-path=optionable/Cargo.toml --no-default-features --features std,derive,chrono,serde_json
          cargo +nightly test --manifest-path=optionable/Cargo.toml --no-default-features --features alloc,derive,chrono,serde_json
          cargo +nightly test --workspace --exclude optionable_k8s_openapi_example --features k8s_openapi_v1_30,kube,k8s_openapi_convert
          cargo +nightly test --workspace --exclude optionable_k8s_openapi_example --features k8s_openapi_v1_31,kube,k8s_openapi_convert
          cargo +nightly test --workspace --exclude optionable_k8s_openapi_example --features k8s_openapi_v1_32,kube,k8s_openapi_convert
          cargo +nightly test --workspace --exclude optionable_k8s_openapi_example --features k8s_openapi_v1_33,kube,k8s_openapi_convert
          cargo +nightly test --workspace --exclude optionable_k8s_openapi_example --features k8s_openapi_v1_34,kube,k8s_openapi_convert
          cargo clippy --features std,derive,chrono,serde_json,k8s_openapi_v1_34,kube
          cargo install cargo-msrv --locked
          cargo msrv verify --path optionable_codegen
          cargo msrv verify --path optionable_derive
          cargo msrv verify --path optionable
          cargo install --locked cargo-deny
          cargo deny check license
      - name: Test orphanrule circumvention (that it compiles)
        run: cd example/orphanrule && cargo run
      - name: Setup kind for integration test of k8s types
        uses: helm/kind-action@v1
      - name: Test deployment server-side-apply
        run: |-
          cd example/k8s/
          kubectl apply -f deployment.yaml
          cargo run --bin apply_deployment
          if [[ $(kubectl get deployment test -o jsonpath='{.spec.replicas}') -ne 2 ]]; then
              exit 1
          fi
          cargo run --bin extract_deployment
      - name: Test CRD server-side-apply
        run: |-
          cd example/k8s/
          cargo run --bin crd | kubectl apply -f -
          kubectl apply -f cr.yaml
          cargo run --bin apply_crd
          if [[ $(kubectl get customcrd test -o jsonpath='{.spec.template.type}') -ne "v1beta1" ]]; then
              exit 1
          fi
          cargo run --bin extract_crd
      - name: Run release-plz
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.release }}
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_CARGO_REGISTRY_TOKEN }}
