name: Release-plz

permissions:
  contents: write

on:
  workflow_dispatch: { }

jobs:
  # Release unpublished packages.
  release-plz-release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged }}
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Pre-release tests
        run: |-
          cargo +nightly doc --manifest-path=optionable/Cargo.toml --features serde_json/std,serde_json,derive
          cargo +nightly test --features k8s_openapi_v1_30
          cargo +nightly test --features k8s_openapi_v1_31
          cargo +nightly test --features k8s_openapi_v1_32
          cargo +nightly test --features k8s_openapi_v1_33
          cargo +nightly test --features k8s_openapi_v1_34
          cargo +nightly test --manifest-path=optionable/Cargo.toml --no-default-features --features derive,chrono,serde_json
          cargo +nightly test --manifest-path=optionable/Cargo.toml --no-default-features --features std,derive,chrono,serde_json
          cargo +nightly test --manifest-path=optionable/Cargo.toml --no-default-features --features alloc,derive,chrono,serde_json
          cargo clippy --features k8s_openapi_v1_34
          cargo install --locked cargo-deny
          cargo deny check license
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_CARGO_REGISTRY_TOKEN }}
