name: Release-plz

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release:
        description: Whether to actually run release-plz
        type: boolean
        required: true

jobs:
  k8s-openapi-roundtrip:
    name: k8s-openapi roundtrip test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: k8s-openapi roundtrip test
        run: ./k8s_openapi_roundtrip.sh
        working-directory: testscripts
  release-plz-release:
    needs: k8s-openapi-roundtrip
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-audit, cargo-deny and cargo-msrv
        run: |-
          cargo install cargo-audit --locked
          cargo install cargo-msrv --locked
          cargo install --locked cargo-deny
      - name: Pre-release tests
        run: |-
          ./code.sh
          ./other.sh
        working-directory: testscripts
      - name: Test orphanrule circumvention (that it compiles)
        run: cd example/orphanrule && cargo run
      - name: Setup kind for integration test of k8s types
        uses: helm/kind-action@v1
      - name: Test deployment server-side-apply
        run: |-
          cd example/k8s/
          kubectl apply -f deployment.yaml
          cargo run --bin apply_deployment
          if [[ $(kubectl get deployment test -o jsonpath='{.spec.replicas}') -ne 2 ]]; then
              exit 1
          fi
          cargo run --bin extract_deployment
      - name: Test CRD server-side-apply
        run: |-
          cd example/k8s/
          cargo run --bin crd | kubectl apply -f -
          kubectl apply -f cr.yaml
          cargo run --bin apply_crd
          if [[ $(kubectl get customcrd test -o jsonpath='{.spec.template.type}') -ne "v1beta1" ]]; then
              exit 1
          fi
          cargo run --bin extract_crd
      - name: Run release-plz
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.release }}
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_CARGO_REGISTRY_TOKEN }}
